### ISSUE TITLE
It is unclear how to filter using timestamp in the alerts API (potentially not working?)

### ISSUE THREAD

**Issue by grantcurell** [dell/OpenManage-Enterprise#101]
The documentation says the fields sholud be TimeStampBegin and TimeStampEnd

![image](https://user-images.githubusercontent.com/35169230/99907325-33336200-2caa-11eb-9ee8-44e4671b8138.png)

Testing with: `https://192.168.1.93/api/AlertService/Alerts?$filter=TimeStampEnd eq '2020-11-05T23:59:59-05:00'` fails. I pulled the request out of the UI to test:

![image](https://user-images.githubusercontent.com/35169230/99907353-5fe77980-2caa-11eb-8eb5-e7e6cc2a40a6.png)

however it generates a different field altogether: `https://192.168.1.93/core/api/Console/AlertsByFilter?take=30&skip=0&acknowledge=2000&endtime='2020-11-05T23:59:59-05:00'&__=1606056773196`

The `&__=1606056773196`  portion looks to be an Epoch and correlates to the current date.

![image](https://user-images.githubusercontent.com/35169230/99907456-df754880-2caa-11eb-88e5-5b24f90a08fa.png)

I tried modifying my request to: `https://192.168.1.93/api/AlertService/Alerts?$filter=endtime eq '2020-11-05T23:59:59-05:00'` and it is still rejected with:

```
{
  "error": {
    "code": "Base.1.0.GeneralError",
    "message": "A general error has occurred. See ExtendedInfo for more information.",
    "@Message.ExtendedInfo": [
      {
        "MessageId": "CGEN1002",
        "RelatedProperties": [],
        "Message": "Unable to complete the operation because the requested URI is invalid.",
        "MessageArgs": [],
        "Severity": "Critical",
        "Resolution": "Enter a valid URI and retry the operation."
      }
    ]
  }
}
```

There doesn't seem to be any mention in the docs of how to use this field correctly. I can't tell if the correct field is endtime or TimeStampEnd or what the correct syntax is. I also tried modifying my URL to include an epoch with `https://192.168.1.93/api/AlertService/Alerts?$filter=endtime%20eq%20%272020-11-05T23:59:59-05:00%27&__=1606056773196` and that was also rejected.

**Comment by alfredocolon** [comment]
I'm working a project to query alerts based on date/time, so this Issue is of importance to me.  @grantcurell, would it help if I as a Dell customer opened a support ticket regarding this?  I note that this was opened nearly a year ago and still hasn't been addressed.  Or am I wrong?

**Comment by RaajeevKalyan** [comment]
This seems to be incorrectly documented - the response for an Alert should indicate a single field for the timestamp demarcated by TimeStamp. One should be able to filter on this - from what I remember only the ge/le operators were implemented and not gt/lt. An example is below with a basic GET on all Alerts showing 362 alerts

https://<redacted ip>/api/AlertService/Alerts
 "@odata.context": "/api/$metadata#Collection(AlertService.Alert)",
    "**@odata.count": 362,**
    "value": [
        {
            "@odata.type": "#AlertService.Alert",
            "@odata.id": "/api/AlertService/Alerts(362)",
            "Id": 362,
            "SeverityType": 16,
            "SeverityName": "Critical",
            "AlertEntityId": 10127,
            "AlertEntityName": "redacted",
            "AlertEntityType": "Device",
            "AlertDeviceId": 10127,
            "AlertDeviceName": "redacted",
            "AlertDeviceType": 1000,
            "AlertDeviceIpAddress": "redacted",
            "AlertDeviceMacAddress": "redacted",
            "AlertDeviceIdentifier": "",
            "AlertDeviceAssetTag": "",
            "DefinitionId": 400021,
            "CatalogName": "Application",
            "CategoryId": 1,
            "CategoryName": "System Health",
            "SubCategoryId": 90,
            "SubCategoryName": "Devices",
            "StatusType": 2000,
            "StatusName": "Not-Acknowledged",
            **"TimeStamp": "2021-09-07 19:01:28.46",**
            "Message": "Unable to perform the operation on the device because connection with the device is lost. ",
            "EemiMessage": "The operation cannot be performed on the device because connection with the device is lost.",
            "RecommendedAction": "Check if the device has power and is turned on, if device is not powered on then attempt iDrac Reset. If issue still not resolved, then attempt a virtual reseat. If the issue persists after performing the above steps, contact your service provider.",
            "AlertMessageId": "CDEV6131",
            "AlertVarBindDetails": "",
            "AlertMessageType": "Internal",
            "MessageArgs": "",
            "AlertDeviceGroup": 0,
            "UserName": ""
        },


Use of a filter on timestamp - 
https://<redacted ip>/api/AlertService/Alerts?$filter=TimeStamp ge '2021-09-07 19:01:22.483'
{
    "@odata.context": "/api/$metadata#Collection(AlertService.Alert)",
    **"@odata.count": 2,**
    "value": [
        {
            "@odata.type": "#AlertService.Alert",
            "@odata.id": "/api/AlertService/Alerts(362)",
            "Id": 362,
            "SeverityType": 16,
            "SeverityName": "Critical",
            "AlertEntityId": 10127,

**Comment by alfredocolon** [comment]
Thanks @RaajeevKalyan - Have you any idea when the PS script will be updated to incorporate the findings in your post?

**Comment by grantcurell** [comment]
> Thanks @RaajeevKalyan - Have you any idea when the PS script will be updated to incorporate the findings in your post?

Done

**Comment by grantcurell** [comment]
@RaajeevKalyan - do you

**Comment by alfredocolon** [comment]
Thank you very much, @grantcurell and @RaajeevKalyan
