### ISSUE TITLE
set_power_state.py is executed on all servers even when --idrac-ips specifies a single IP

### ISSUE THREAD

**Issue by uzzikie** [dell/OpenManage-Enterprise#115]
ran the following code

`python set_power_state.py --ip <ome_ip> --user <user> --password <password> --idrac-ips 192.168.1.73 --state MASTER_BUS_RESET`

but seems like it got executed on all servers instead. Target system names are hidden.
User only has DEVICE_MANAGER privileges 

![Screenshot 2020-12-01 at 8 06 57 AM](https://user-images.githubusercontent.com/13991294/100680453-8a24ef80-33ac-11eb-8865-b75577d573ed.png)

on OME Version 3.4.0 (Build 55) , using python 3.7

**Comment by grantcurell** [comment]
@uzzikie apologies on the delayed response. I haven't used that script before - I'll take a look tomorrow.

**Comment by grantcurell** [comment]
@uzzikie Oh, I just saw what OME version you have - there's a known bug. If you update that will go away. See: https://github.com/dell/OpenManage-Enterprise/issues/81

**Comment by uzzikie** [comment]
that's a terrible bug! I'll update OME and monitor if that resolves the situation. Thanks for looking into it

**Comment by grantcurell** [comment]
@uzzikie definitely let me know if you still have problems. Running on my up-to-date instance cleared up any problems for me, but I wasn't able to confirm if things got cleared up with the user from #81 

If it's doing that for you on the up-to-date version it's definitely something I want to get fixed 😂

**Comment by grantcurell** [comment]
@uzzikie did this behave as expected for you?

**Comment by uzzikie** [comment]
i haven't gonna around to update the OME yet....hopefully sometime this week

**Comment by uzzikie** [comment]
just updated to Version 3.5.0 (Build 60) and ran POWER_ON instead

`python set_power_state.py --ip <ome_ip> --user <user> --password <password> --idrac-ips 192.168.1.73 --state POWER_ON`

![Screenshot 2020-12-09 at 8 16 26 AM](https://user-images.githubusercontent.com/13991294/101557122-4c047d00-39f7-11eb-8911-219c4dd937b9.png)

unfortunately it's still executing on all servers

I did my own tests by using Postman and sent the JSON directly to OME
```
{
  "Id": 0,
  "JobName": "Power operation",
  "JobDescription": "Performing a power operation - Power On",
  "State": "Enabled",
  "Schedule": "startnow",
  "JobType": {
    "Name": "DeviceAction_Task"
  },
  "Targets": [
    {
      "Id": 10315,
      "Data": "",
      "TargetType": {
        "Id": 1000,
        "Name": "DEVICE"
      }
    }
  ],
  "Params": [
    {
      "Key": "override",
      "Value": "true"
    },
    {
      "Key": "powerState",
      "Value": "2"
    },
    {
      "Key": "operationName",
      "Value": "POWER_CONTROL"
    },
    {
      "Key": "deviceTypes",
      "Value": "1000"
    }
  ]
}
```
and it worked as expected; the command was only executed on the target server

![Screenshot 2020-12-09 at 8 36 50 AM](https://user-images.githubusercontent.com/13991294/101558401-da79fe00-39f9-11eb-81b0-e1b7aef8f633.png)

I think you might have to look into the script why it's this is happening

**Comment by grantcurell** [comment]
@uzzikie I figured it out. The code for this was borrowed from elsewhere:

![image](https://user-images.githubusercontent.com/35169230/101559815-e9c46180-398f-11eb-8bde-c1d59fa457b4.png)

groupname was defaulting to All Devices. I'm sorry I put you through upgrading on this one man. I saw this one and the version you were running and figured it was related to the last bug. It's fixed now.

**Comment by uzzikie** [comment]
thanks! appreciate your fine work on this
