### ISSUE TITLE
Passwords should not be required on the command line

### ISSUE THREAD

**Issue by 5nafu** [dell/OpenManage-Enterprise#118]
Scrolling through the `get_device_list.py` example, I realised that at least in this file it is required to add the password on the command line. 
This is a very bad practice as everyone with access to the process tree (`ps -a`) can read the password.

It would be better to ask for the password, if it is not set. You could use `getpass.getpass` for this, to not leak the information on screen.

**Comment by grantcurell** [comment]
@5nafu - I can look into getpass, that said, if someone is running `ps` on your system with privileges sufficient to see your process calls, then they could also just read the password out of memory since Python stores it in plaintext.

**Comment by grantcurell** [comment]
> Scrolling through the `get_device_list.py` example, I realised that at least in this file it is required to add the password on the command line.
> This is a very bad practice as everyone with access to the process tree (`ps -a`) can read the password.
> 
> It would be better to ask for the password, if it is not set. You could use `getpass.getpass` for this, to not leak the information on screen.

I can look into `getpass`. Appreciate the heads up. Honestly I thought the value of hidepid was 1 these days, but Google shows me that for whatever reason even RHEL still defaults it to 0.

**Comment by 5nafu** [comment]
> Honestly I thought the value of hidepid was 1 these days, but Google shows me that for whatever reason even RHEL still defaults it to 0.

dame goes for Ubuntu (20.04), where `/proc` is mounted without any `hidepid` and I can read `/proc/[anypid]/cmdline` as normal user.

I am happy to create a pull request for you to fix this, it will come up shortly. 
It is no big deal, actually, as you only need to import `getpass.getpass` and then use it if no password is set:
``` python
from getpass import getpass
# [...]
if __name__ == '__main__':
    # [...]
    parser.add_argument("--password", "-p", required=False, help="Password for MSM")
    #                                                ^^^^^^
    # [...]
    args = parser.parse_args()
    if not args.password:
        args.password = getpass()
    # [...]
```

**Comment by grantcurell** [comment]
@5nafu I really appreciate your taking the time man!
