### ISSUE TITLE
run_existing_report.py script generating duplicate device names

### ISSUE THREAD

**Issue by mprreddy51** [dell/OpenManage-Enterprise#12]
I schedule a custom report with below fields in OME and ran custom csv report.
 
From  the CSV report I filtered out only Component Name =  "PowerEdge Server BIOS" . I observed there are some duplicates Entries showing in CSV in the  "Device Name" Column and  Total Device count shows correct number.

Device Name ,Device Identifier,Device Type,Device Model,Component Name,Current Version ,Available Version,Compliance Status,Baseline Name

**Comment by prasadrao-dell** [comment]
Checked with the BIOS report as well as with Alert reports. The duplicate entries are coming from the OME backend and needs to be fixed there. The fix is not applicable to these scripts.
