### ISSUE TITLE
discover_device.py - multiply discovery groups

### ISSUE THREAD

**Issue by markatdxb** [dell/OpenManage-Enterprise#13]
hello, thanks for providing all these scripts, they are really super helpful for our automation processes. 
one thing i wanted to ask as im not that proficient in python. 
would be possible in the discover_device.py  to add check whether the discovery group already exists - and if yes then modify existing discovery group instead of creating duplicate ? Thanks

**Comment by RaajeevKalyan** [comment]
Dell Customer Communication - Confidential

There should be a script that takes in a job pattern and tries to modify it / re-run it - could you check if modify_discovery_job.py in the same repo does what you need

Raajeev

**Comment by markatdxb** [comment]
Thanks for feedback. I was looking that the modify discovery script just I'm not clear if that script just modify existing discovery groups or also create new ones of no group exists.

**Comment by prasadrao-dell** [comment]
@markatdxb 
1. discover_device.py 
- always creates a new discovery job and run the job on the IPs that were provided as input.
2. modify_discovery_job.py
- Allows to input a job name that can be modified to include the additional IPs(also input) and runs them.

Therefore it appears that your need to satisfied through the 2nd script.
If not, please provide some more information regarding your use case.

**Comment by prasadrao-dell** [comment]
Beleive the user concern is addressed via the modify_discovery_job.py script.
Request to reopen the issue in case of any new inputs.
