### ISSUE TITLE
Ability to sync common settings between OME's

### ISSUE THREAD

**Issue by SmrtAss** [dell/OpenManage-Enterprise#153]
We run 10 OME's, Id like the ability to sync settings between multiple OME's with ease.  Settings like all Compliance Profiles, ALL Firmware Catalogs, Templates,  SNMP, Warranty, Alert Settings, and other Application Settings, Basically if its a "general setting" that isnt site or system specific, id want to replicate it to other sites.

**Comment by grantcurell** [comment]
I can look into doing some of these - unfortunately at the code level "all general settings" is very complex. At some point it makes a lot less sense to do this via the API and a lot more sense to push this as a feature request into OME itself as a full database replication capability. Doing and maintaining everything would basically be an entirely new software product.

Which would be your top three?

**Comment by grantcurell** [comment]
I'm going to close this out - if this is a requirement feel free to comment back and reopen and I'll take a look at it.
