### ISSUE TITLE
OME Devices

### ISSUE THREAD

**Issue by SmrtAss** [dell/OpenManage-Enterprise#155]
Along with creating discovery jobs that create static groups, a script to link/associate/build relationships between static groups and the physical Hierarchy.  We should not be adding the same data multiple times to OME.  1 script / response file should import into static groups, physical hierarchy and whatever future systems require independent delineation.

**Comment by RaajeevKalyan** [comment]
Is this the kind of functionality being asked for here? https://github.com/dell/OpenManage-Enterprise/tree/master/Plugins/Power%20Manager/Import%20Physical%20Hierarchy

**Comment by grantcurell** [comment]
I'm closing this out but if what @RaajeevKalyan doesn't cover your needs feel free to reopen and I'd be happy to take a look at it.
