### ISSUE TITLE
Multiple OME Reporting

### ISSUE THREAD

**Issue by SmrtAss** [dell/OpenManage-Enterprise#156]
"Built in" ability to link multiple OME's with 1 "master" OME that acts as the single pane of glass, reporting all alerting and basic information for reporting.

Eventual to sublet commands to sub OMEs to do actual work, i.e. firmware updates, compliance profile application, etc...

**Comment by RaajeevKalyan** [comment]
This seems like a request for new OME functionality as opposed to a sample script using existing API infrastructure. I will reflect to product management internally, but will close this as no functionality exists at present / product features are not being tracked via this repo.

**Comment by SmrtAss** [comment]
I think it could easily be done by script / api.

Sent from mobile device, please excuse any mistakes.

-------- Original Message --------

**Comment by grantcurell** [comment]
Unfortunately this one is actually outright impossible to do with the API. The programming hooks for this type of functionality simply don't exist - this would have to be a new feature request on the backend of OME. The other two tickets still open though are feasible and I can work those.

That said, @vmallemp is probably the right person to track this.
