### ISSUE TITLE
Invoke-ReportExecution.ps1 missing -OutputFilePath in Example

### ISSUE THREAD

**Issue by ChrisSteinbeisser** [dell/OpenManage-Enterprise#177]
The basic example doesn't work without the -OutPutFilePath parameter ... so maybe add that parameter in the .EXAMPLE for clarity/reference.  Maybe point out  the need of finding the reportID using the Get-ReportList script or a querying to get that ID as well.

EXAMPLE using the .EXAMPLE

PS C:\bin\I_am_wonderful> ./Invoke-ReportExecution.ps1 -IpAddress "100.79.7.15" -Credentials $cred -ReportId 20214
C:\bin\I_am_wonderful\Invoke-ReportExecution.ps1 : Exception occured at line 1 - CSV Filepath is not provided.
At line:1 char:1
+ ./Invoke-ReportExecution.ps1 -IpAddress "100.79.7.15" -Credentials $c ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-ReportExecution.ps1

**Comment by grantcurell** [comment]
This is another one that needs to be overhauled anyway. I'll take a look.

**Comment by grantcurell** [comment]
I'll have a PS7 version of this up today so you can use this with get-reports

**Comment by grantcurell** [comment]
@ChrisSteinbeisser let me know if the new script gives you any trouble.

**Comment by ChrisSteinbeisser** [comment]
Will do... I will be testing it and demo'ing with some folks next week.  I'll also refer folks to submit something via Issue 181 if they have concerns/needs for PS 5.1. (I'm liking the new name or id parameter you added.  Thanks!

**Comment by grantcurell** [comment]
@ChrisSteinbeisser hahaha I always add that - if nothing else I know I don't like to have to find the ID hahaha

If the customer has any other feedback feel free to post it.

Worst case scenario is it's not a common need and it sits in the queue
