### ISSUE TITLE
OME Support Assist powershell plugin example

### ISSUE THREAD

**Issue by brucekamp** [dell/OpenManage-Enterprise#192]
Are there any plans for support assist plugins with powershell?  I am looking to create support assist groups plugin group based on the datacenter name & operating system from OME.

**Comment by ChrisSteinbeisser** [comment]
FYI ... working with Bruce on requirements here but feel free to ping me as well on this enhancement.

**Comment by ChrisSteinbeisser** [comment]
Bruce mentioned he's looking for a PowerShell example around this URI:https://{hostname}/api
/SupportAssistService/Actions/SupportAssistService.AddMemberDevices

**Comment by grantcurell** [comment]
@brucekamp yes - the main roadblock has been my inability to get into the system that allows us to generate pins for SupportAssist. I gave it a shot a week ago and there are some pieces of the puzzle missing for me. If you guys know how to get that set up I can work tickets #136-139 which are the SupportAssist tickets I'm currently tracking

**Comment by ChrisSteinbeisser** [comment]
Grant ... Bruce is from Burlington Northern Santa Fe(BNSF) so he wouldn't know what we mean by pins.  I'll ping another OSE/cc' you, as I believe he was the one who set up our pins in the OSE lab.

**Comment by grantcurell** [comment]
@ChrisSteinbeisser I'll work it tomorrow morning! Saw your email - appreciate the help.

@brucekamp something like adding devices shouldn't be a problem

**Comment by grantcurell** [comment]
Got access to a dev setup. I'll start work on it tomorrow.

**Comment by grantcurell** [comment]
@brucekamp - are you able to use PS7?

**Comment by brucekamp** [comment]
Yes


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by grantcurell** [comment]
@ChrisSteinbeisser I'm not sure that URI is active yet:

![image](https://user-images.githubusercontent.com/35169230/108117648-305aca00-706b-11eb-81e0-d579a487c18c.png)

It's also not documented yet in the API catalog. Will report back when I know more

**Comment by grantcurell** [comment]
I talk to PG and figured out the API calls for this. I'm not familiar, but I'm teaching myself now and working up some code. @brucekamp just confirming the functionality I have planned will cover your use case:

- add/remove a group
- add/remove a device from that target group

**Comment by brucekamp** [comment]
Perfect!


Thanks,
Bruce Kamp
Windows Administrator
P: 817-352-1372

**Comment by grantcurell** [comment]
Haven't forgotten this. Was out last week working on a different project. Working on this right now.

**Comment by ChrisSteinbeisser** [comment]
Perfect!

**Comment by grantcurell** [comment]
@brucekamp - the code is complete. The docs are available here: https://github.com/dell/OpenManage-Enterprise/blob/master/docs/API.md#invoke-manage-supportassist-groups

**Comment by grantcurell** [comment]
If you run into any problems feel free to open a ticket on it!

**Comment by grantcurell** [comment]
If you run into any problems feel free to reopen this ticket!
