### ISSUE TITLE
Authentification process

### ISSUE THREAD

**Issue by Bruniche** [dell/OpenManage-Enterprise#2]
Hello,

I came here for a specific question about the url for SessionService to having a token.

In all your scripts, you use : **/api/SessionService/Sessions**
with Username & Password as payload.

Personnaly, in the first API guide about OME, the url recommended was :
**/redfish/v1/SessionService/Sessions/Members**
with Username // Password as payload.

Now, if we query GET en /redfish/v1 the new OME 3.2.0, in the return we have :
Links => Sessions => @odata.id or SessionService => @odata.id
Both return : **/redfish/v1/SessionService/Sessions**

But, if we make a POST request on this url
with Username // Password as payload.
=> we have a 500 error in return.

Is it the attented behavior ?
Can we create a token through this url ?
There is no a link between /api & /redfish/v1 ?

Thanks for your help

**Comment by RaajeevKalyan** [comment]
The /redfish/v1/SessionService/Sessions/Members is not in line with Redfish spec. In newer versions of OME the POST on /redfish/v1/SessionService/Sessions should be fixed. I'll confirm the release that the fix is in and edit this comment

**Comment by RaajeevKalyan** [comment]
Issue should be addressed by OME 3.3.1
