### ISSUE TITLE
Add ability to stage for next reboot to firmware update scripts

### ISSUE THREAD

**Issue by TrevorSquillario** [dell/OpenManage-Enterprise#218]
This is a common use case to stage the firmware to be updated on the next reboot. It's often used in conjunction with VUM that will do it's updates then reboot the host. This gives you the ability to do OS and firmware updates in one reboot. 

We can see how this is implemented in the PowerShell Module using the stagingValue attribute https://github.com/dell/OpenManage-PowerShell-Modules/blob/main/DellOpenManage/Public/OME/Update-OMEFirmware.ps1

**Comment by TrevorSquillario** [comment]
Thanks! I'll kick the tires on this one.

**Comment by grantcurell** [comment]
np!
