### ISSUE TITLE
-IdracIps csv file

### ISSUE THREAD

**Issue by sg142** [dell/OpenManage-Enterprise#220]
Trying to input the idrac ip’s using csv instead of entering them in the command line. I tried using csv file and gave the path but it is failing.
 
 
.\Add-DeviceToStaticGroup.ps1' -IpAddress 192.168.1.93 -Credentials $creds -GroupName 'YourGroup' -IdracIps 
    '192.168.1.45,192.168.1.63' -UseDiscoveryJobId 14094

**Comment by grantcurell** [comment]
@sg142 what command are you using to run it and what's the output? (I recognize all those IPs as my own so I assume it's not those 😀)

**Comment by sg142** [comment]
Oops.. I pasted incorrect command.. Here it is
.\ADD-DeviceToStaticGroup.ps1 -IpAddress '10.xx.xx.xx' -Credentials $creds -GroupName 'test01' -IdracIps 'C:\Users\Administrator\Documents\OME_test\ansfile2.csv'  -UseDiscoveryJobId 38174

Write-Error: Exception occured at line 311 - Cannot process argument transformation on parameter 'DeviceIdracIp'. Cannot convert value "C:\Users\Administrator\Documents\OME_test\ansfile2.csv" to type "System.Net.IPAddress". Error: "An invalid IP address was specified."

**Comment by grantcurell** [comment]
It looks like you're passing a CSV file to idrac ips. You can see the help page for a script with `get-help .\Add-DeviceToStaticGroup.ps1 -Detailed`. `-IdracIps` does not accept a file.

![image](https://user-images.githubusercontent.com/35169230/113914953-24a69c80-97ac-11eb-91f5-828b907e89fd.png)

**Comment by grantcurell** [comment]
I'm going to close this but feel free to reopen it if that didn't answer your question!
