### ISSUE TITLE
Add-DeviceToStaticGroup.ps1 

### ISSUE THREAD

**Issue by sg142** [dell/OpenManage-Enterprise#222]
Add-DeviceToStaticGroup.ps1  is taking longer time to add servers into the static group.

**Comment by RaajeevKalyan** [comment]
Please add some more detail - 

What version of OME are you using? Was it recently upgraded etc before you started seeing issues?

What were prior metrics for adding servers into a static group for comparison?

Have you tested out the API independent of the script and have timings that seem different?

**Comment by sg142** [comment]
OME Version 3.5.0 (Build 60)
I just started using it month ago- have same issue
I haven't tested API independent. can you please share that info?

**Comment by RaajeevKalyan** [comment]
The API to use would be a POST on /api/GroupService/Actions/GroupService.AddMemberDevices

Payload would be similar to below except with the group id / device ids you are interested in (Group Id will be derived from a GET on /api/GroupService/Groups and Device IDs from a GET on /api/DeviceService/Devices)

{
 "GroupId": 100,
 "MemberDeviceIds" : [1414, 1464, 1214, 1264]
}
