### ISSUE TITLE
get_group_by_device.py Syntax Error  

### ISSUE THREAD

**Issue by coconut429** [dell/OpenManage-Enterprise#233]
File "get_group_by_device.py", line 60

    def authenticate(ome_ip_address: str, ome_username: str, ome_password: str) -> dict:

                                   ^

SyntaxError: invalid syntax

**Comment by grantcurell** [comment]
Just double checking - this is on Python 3 correct? Looks like that syntax error is pointing at the type definition.

**Comment by coconut429** [comment]
python 2.7.5

我試過之前的 get_group_list 都可以執行

如果需要用Python 3 我就去找環境


Grant Curell ***@***.***> 於 2022年4月15日 週五 下午1:09寫道：

**Comment by coconut429** [comment]
使用python3 是可以執行的

Jeff Yeh ***@***.***> 於 2022年4月15日 週五 下午2:09寫道：
