### ISSUE TITLE
GroupService has no RemoveMemberDevices method?

### ISSUE THREAD

**Issue by grantcurell** [dell/OpenManage-Enterprise#32]
From [page 297 of the API guide](https://topics-cdn.dell.com/pdf/dell-openmanage-enterprise_api-guide5_en-us.pdf) I see a way to add member devices to a static group, but I don't see a way to remove them.

Is that by design or is there a way to do that?

I also don't see a way to delete a group that already exists.

Edit: What I ultimately want to be able to do is move servers between groups.

**Comment by RaajeevKalyan** [comment]
This is not functionality common to both consoles (OME and OME-M) - these APIs are documented in the GroupService actions specific to OME (pages 535 and later)

POST on /api/GroupService/Actions/
GroupService.RemoveMemberDevices should remove devices from groups

POST on /api/GroupService/Actions/GroupService.DeleteGroup should delete the created groups

**Comment by RaajeevKalyan** [comment]
I'll close this as it looks like this is a non-issue - let me know if you disagree / this needs to be revisited
