### ISSUE TITLE
Need Powershell script to run inventory on selected devices / all devices within a group

### ISSUE THREAD

**Issue by RaajeevKalyan** [dell/OpenManage-Enterprise#45]
POST on JobService/Jobs with sample payload below tuned to specific devices 

{
  "Id": 0,
  "JobName": "Inventory job for foo devices ",
  "JobDescription": "Inventory job for foo devices",
  "Schedule": "startnow",
  "State": "Enabled",
  "JobType": {
    "Name": "Inventory_Task"
  },
  "Targets": [
    {
      "Id": <device_id>,
      "Data": "",
      "TargetType": {
        "Id": 1000,
        "Name": "DEVICE"
      }
    }
  ]
}

**Comment by grantcurell** [comment]
I think this can be closed. It should be addressed with: https://github.com/dell/OpenManage-Enterprise/pull/70

**Comment by grantcurell** [comment]
Since I already wrote https://github.com/dell/OpenManage-Enterprise/pull/70 I'll take this one if you want to assign it to me.

**Comment by grantcurell** [comment]
Completed in https://github.com/dell/OpenManage-Enterprise/pull/85
