### ISSUE TITLE
Need powershell Get-OMEntUser.ps1, New-OMEntUser.ps1 example scripts

### ISSUE THREAD

**Issue by ChrisSteinbeisser** [dell/OpenManage-Enterprise#47]
Raajeev Kalyanaraman ... I used your Get-DeviceList and New-StaticGroup scripts to create some examples for Getting users and creating users in OpenManage.  Working on setting up Github but attached are the examples that I am looking for... hope it's ok I put myself as author.  Let me know if you want me to credit you as well.

[New-OMEntUser.ps1.txt](https://github.com/dell/OpenManage-Enterprise/files/5229426/New-OMEntUser.ps1.txt)
[Get-OMEntUser.ps1.txt](https://github.com/dell/OpenManage-Enterprise/files/5229428/Get-OMEntUser.ps1.txt)

**Comment by RaajeevKalyan** [comment]
Chris - could you please submit these in a Pull Request so we can go over and merge. In addition would it be possible to add in a Python version of these scripts too?

**Comment by ChrisSteinbeisser** [comment]
Yes… sorry was out on vacation last week but back yesterday.  I’ll try to work up the Python ones and work with Trevor Squillario(OSE peer of mine) on doing a pull request… Trevor also recommended a couple good tweaks that I want to do… but yes… definitely planning on putting those out there the right way in the next week or so.

Thanks,


Chris Steinbeisser
Principal Engineer, Product Technologist (OSE)
Dell Technologies | Data Center Compute and Solutions (DCCS)
North America Enterprise
Office +1-214-310-2569 Mobile +1-214-310-2569
Chris.Steinbeisser@dell.com<mailto:Chris.Steinbeisser@dell.com>

**Comment by grantcurell** [comment]
I have brought both scripts up to spec for the contributor guide and incorporated them in the repo.
