### ISSUE TITLE
Need script for getting the virtual appliance settings.

### ISSUE THREAD

**Issue by vmallemp** [dell/OpenManage-Enterprise#48]
Request was to save the current settings of the appliance and have the ability to change/modify them.

**Comment by grantcurell** [comment]
Were there specific settings for this they were looking for? Is this referring to the entire configuration of OME?

**Comment by vmallemp** [comment]
Entire configuration of the OME

**Comment by grantcurell** [comment]
Update - this might be a feature in OME, but probably won't be done via a script.
