### ISSUE TITLE
update_firmware_using_catalog.py is not python3 compliance

### ISSUE THREAD

**Issue by justinrush** [dell/OpenManage-Enterprise#5]
line 367 does this:
```python
data = json.loads(request.obj.data)
```
this will throw a TypeError: the JSON object must be str, not 'bytes'

you need to either do:
```python
data = json.loads(request.text)
```
or just leverage the .json property of the requests object
```python
data = request.json()
```

I'm sure there are other things, but i stopped looking when I found that python2 just works.

**Comment by RaajeevKalyan** [comment]
This should have been fixed via recent updates - could you please recheck if something doesn't work in your environment
