### ISSUE TITLE
Script to filter alert logs by type of logs. 

### ISSUE THREAD

**Issue by vmallemp** [dell/OpenManage-Enterprise#50]
Can the script **get_alerts_by_group.py** be enhanced to filter alert logs by type of logs (ex - hardware logs etc)?

**Comment by grantcurell** [comment]
@vmallemp you can filter alerts by any odata filter. There's a list available on page 75 [here](https://dl.dell.com/topicspdf/dell-openmanage-enterprise_api-guide2_en-us.pdf). Is there something in particular you'd like it to do?

**Comment by grantcurell** [comment]
Clarification received. Need to be able to filter on attributes

See page 75 of the API guide

**Comment by grantcurell** [comment]
Finished in https://github.com/dell/OpenManage-Enterprise/pull/103
