### ISSUE TITLE
Need a script for reading and replicating VLANs

### ISSUE THREAD

**Issue by vmallemp** [dell/OpenManage-Enterprise#51]
Need a script to do the following:

1.	Read the vlans available on a source chassis using REST APIs [Source chassis ip, username, password, https port must be provided by the user]
2.	Replicate the vlans on a number of target chassis using REST APIs [Target chassis ip, username, password, https port must be provided by the user]
3.	If the target chassis already has vlan that overlaps with the source vlan, skip replicating that vlan on target.

**Comment by grantcurell** [comment]
What is meant by adding a VLAN to the chassis? Is there a particular chassis the customer has in mind? Do they mean the switch on the chassis?

**Comment by grantcurell** [comment]
Clarification received. Use these scripts as baselines. Credit goes to Hemanth Vishwanath

[vlan_replicator.py.txt](https://github.com/dell/OpenManage-Enterprise/files/5598577/vlan_replicator.py.txt)
[inputs.json.txt](https://github.com/dell/OpenManage-Enterprise/files/5598578/inputs.json.txt)
