### ISSUE TITLE
Need a script to create a group based on IP addresses 

### ISSUE THREAD

**Issue by vmallemp** [dell/OpenManage-Enterprise#52]
Customer wants to create query groups based on site IP addresses or subnet. Should have the option to move servers from one group to another.

**Comment by grantcurell** [comment]
I would be willing to work on this - just to clarify, they want to provide a subnet and then based on that subnet's range the code should select all servers in that subnet and then assign them to a group?

**Comment by grantcurell** [comment]
Clarification obtained - this needs to enhance the discovery to also create a group of the discovered devices.
