### ISSUE TITLE
Get the list of available firmware baselines for a host

### ISSUE THREAD

**Issue by vmallemp** [dell/OpenManage-Enterprise#53]
Customer wants to list available baselines for a host in OME with APIs. Wants to achieve the same functionality as available in the UI on the firmware tab of a host:

[Customer request.docx](https://github.com/dell/OpenManage-Enterprise/files/5247041/Customer.request.docx)

**Comment by grantcurell** [comment]
I'll work this - you can assign it to me if you want.

**Comment by grantcurell** [comment]
Completed with https://github.com/dell/OpenManage-Enterprise/pull/59
