### ISSUE TITLE
Need a script to get audit logs and purge them weekly

### ISSUE THREAD

**Issue by vmallemp** [dell/OpenManage-Enterprise#54]
Ability to create a job that will get all the audit logs and then purge them to a a remote file share once a week as part of security requirements.

**Comment by grantcurell** [comment]
Does this need to support Kerberos auth?

**Comment by grantcurell** [comment]
Resolved by https://github.com/dell/OpenManage-Enterprise/pull/71

I didn't see a way to purge the logs. This may need to be solved separately, but it does the rest.

**Comment by RaajeevKalyan** [comment]
Audit logs on the system cannot be purged - the ability to export is all that is present within OME
