### ISSUE TITLE
Need a script to initiate Configuration Inventory

### ISSUE THREAD

**Issue by markatdxb** [dell/OpenManage-Enterprise#58]
Hello, im looking for a script which would kick off collection of Configuration data from single or multiple iDRACs 
Currently as far as im aware there is only schedule job in OME which performs the collection on daily basis, but as for our automation approach i would like the ability to start the process via REST or script for single iDRAC
thx

**Comment by grantcurell** [comment]
I'd be willing to take a look at it. I'm not sure what is meant by configuration data though - do you have a screenshot or something?

**Comment by markatdxb** [comment]
Hi, pls see attached. 
Our plan is to fully automated the new iDrac configuration process.
- discover iDrac in OME
- upgrade to the latest FW 
- apply the company standard configuration to iDrac

Our current process:
- we initiate python script to discover new Device in OME - this script is avail on GitHub in Dell repo
- next what we want to do:
1. run script to collect Configuration Inventory Data ( OME has scheduled job which runs once per day for all devices ) for new device. This is important in order to be able to compare existing iDrac configuration to Configuration Template settings
2. run another script which would assign the Configuration Template to new Device and run remediation ( this would configure the new iDrac as per our requirements )

Let me know if you would need any more details

![image](https://user-images.githubusercontent.com/43998117/97834515-9d3f9380-1d0a-11eb-8cca-0f3b31b5d7fe.png)

**Comment by grantcurell** [comment]
@markatdxb - I haven't used that functionality before. I'll take a look and report back here!

**Comment by grantcurell** [comment]
@markatdxb - Just wanted to give you a heads up I think I have a working solution. Took me a bit because it required an undocumented API call and had to study up on how the configuration inventory specifically worked. I'll PR it here tomorrow.

**Comment by grantcurell** [comment]
Request completed in that PR in Python.

**Comment by grantcurell** [comment]
Resolved with https://github.com/dell/OpenManage-Enterprise/pull/70. PowerShell parity requirement ticket is here https://github.com/dell/OpenManage-Enterprise/issues/45

**Comment by grantcurell** [comment]
@markatdxb - did this do what you were looking for?

**Comment by markatdxb** [comment]
Sorry i cant find your script refresh_device_inventory in repo

**Comment by RaajeevKalyan** [comment]
I think it was renamed -https://github.com/dell/OpenManage-Enterprise/blob/master/Core/Python/invoke_refresh_inventory.py

**Comment by grantcurell** [comment]
Sorry about that - I updated the names so PowerShell and Python matched. The scripts are also now listed [here](https://github.com/dell/OpenManage-Enterprise/blob/master/docs/API.md)

**Comment by markatdxb** [comment]
@grantcurell - just tested the script. i specified single idrac IP but log shows inventory refresh runs on all devices

**Comment by grantcurell** [comment]
@markatdxb huh - I just hopped in bed. I'll give it a go tomorrow and see what's up.

**Comment by RaajeevKalyan** [comment]
Possible I am missing something, but on a quick skim, It looks like your default is to not skip the config inventory - if no group name is specified I think after refreshing the inventory the script will go through and default to running config inventory on the All Devices Group - 

@markatdxb  - could you retry setting the -skip flag to true?

**Comment by markatdxb** [comment]
just tested to add  --skip-config-inventory  - didnt work - it ran but didnt pull configuration data

**Comment by grantcurell** [comment]
@markatdxb on the way back home from a morning meeting now - I'll take a look. Just to clarify though, if you skip config inventory the tab under devices *does not* update

Only the firmware versions and stuff

**Comment by grantcurell** [comment]
@markatdxb - I was able to replicate the problem. The regular inventory refreshes as expected, but the config inventory is targeting all servers. I'm checking it out now.

**Comment by grantcurell** [comment]
@markatdxb - at first I thought there was a problem, but then I remembered the config inventory operates on the configuration group. See help text:

```
    parser.add_argument("--groupname", "-g", required=False, default="All Devices",
                        help="The name of the group containing the devices whose inventory you want to refresh. "
                             "Defaults to all devices. Due to the way the API functions, if you want to refresh the "
                             "configuration inventory, you must have all applicable devices in a group. The "
                             "configuration inventory is specific to the tab called \"Configuration Inventory\" under "
                             "a device's view. You can use the create_static_group and add_device_to_static group "
```

**Comment by markatdxb** [comment]
@grantcurell - if I understand above correctly I need to put device to some temp group first, run the script and remove device from the group?

**Comment by grantcurell** [comment]
@markatdxb unfortunately yes. That's for the configuration inventory only (the tab as shown below)

![image](https://user-images.githubusercontent.com/35169230/99810326-9211a380-2b11-11eb-96ff-a0838e9cb9a9.png)

for just refreshing the firmware list and all that you don't need the group. The config inventory is the same as this button:

![image](https://user-images.githubusercontent.com/35169230/99810456-b9687080-2b11-11eb-9dcc-a0756286de9e.png)

The regular inventory is the same as pressing this button: 

![image](https://user-images.githubusercontent.com/35169230/99810519-d43ae500-2b11-11eb-83b9-6200352192d1.png)

I actually didn't know there was a distinction until I wrote this code 😂

**Comment by grantcurell** [comment]
I just added a warning that will give people a heads up.
