### ISSUE TITLE
get-devicelist.ps1 line 78... backticks are removed after interpolation 

### ISSUE THREAD

**Issue by jzcmyz** [dell/OpenManage-Enterprise#6]
$DeviceCountUrl   = "https://$($IpAddress)/api/DeviceService/Devices?`$count=true&`$top=0"    

should look something like 

$DeviceCountUrl   = "https://$($IpAddress)/api/DeviceService/Devices?`" + '`$count=true&`$top=0'  

Line 78 does not copy and paste very well here

**Comment by vittalreddy** [comment]
Fixed the issue and pushed the changes to master after testing in my environment.
