### ISSUE TITLE
odata filters not implemented / not working universally?

### ISSUE THREAD

**Issue by grantcurell** [dell/OpenManage-Enterprise#68]
I'm new to odata filters, but it doesn't seem like the API implements them universally and it's not clear which ones work and which ones don't. Ex:

`requests.get("https://192.168.1.93/api/DeviceService/Devices?$filter=DeviceName eq \'192.168.1.45\'", headers=authenticated_headers, verify=False)`

This python works and properly returns a 200. However:

`requests.get("https://192.168.1.93/api/DiscoveryConfigService/Jobs?$filter=JobId eq \'10068\'", headers=authenticated_headers, verify=False)`

Fails with:

```
{
  "error": {
    "code": "Base.1.0.GeneralError",
    "message": "A general error has occurred. See ExtendedInfo for more information.",
    "@Message.ExtendedInfo": [
      {
        "MessageId": "CGEN1002",
        "RelatedProperties": [],
        "Message": "Unable to complete the operation because the requested URI is invalid.",
        "MessageArgs": [],
        "Severity": "Critical",
        "Resolution": "Enter a valid URI and retry the operation."
      }
    ]
  }
}
```

Error code is 400.

**Comment by RaajeevKalyan** [comment]
Supported filters should be documented in the REST API guide for GET calls - the examples are not universally required filters afaik and the implementation of a filter is up to the backend. 

I'd recommend closing this - if there is a property that is called out as being supported by a filter query and it does not work, that would be useful to know.
