### ISSUE TITLE
Get-DeviceList.ps1 is broken

### ISSUE THREAD

**Issue by grantcurell** [dell/OpenManage-Enterprise#72]
Running `Get-DeviceList.ps1` doesn't seem to do anything `Get-DeviceList -IpAddress 100.96.20.132 -OutFormat json -UserName admin -Outfilepath C:\Users\Desktop\test.json` . Running the script just causes it to return immediately with no output.

**Comment by RaajeevKalyan** [comment]
Unsure if this was done by mistake / was an issue during merge of a PR - I've fixed the issue for now
