### ISSUE TITLE
Need Python parity for Get-InventoryByType

### ISSUE THREAD

**Issue by grantcurell** [dell/OpenManage-Enterprise#75]
It looks like we are missing the parity script for Get-InventoryByType.

Update:

Based on feedback from @RaajeevKalyan below changing ticket purpose. Need to update Get-DeviceInventory.ps1 to mirror get_device_inventory.py and then remove Get-InventoryByType.

**Comment by RaajeevKalyan** [comment]
Already present in the get_device_inventory.py script - 

 parser.add_argument("--inventorytype", "-invtype", required=False,
                        choices=('cpus', 'os', 'disks', 'controllers', 'memory'),
                        help="Get inventory by cpus/os/disks/controllers,memory")

**Comment by grantcurell** [comment]
I'll make sure to find a way to address this in the documentation
