### ISSUE TITLE
update_firmware_using_catalog.py with OME 3.5.0 (Build60)

### ISSUE THREAD

**Issue by Thibaudm33** [dell/OpenManage-Enterprise#81]
Hi,

this morning we had an issue with your script update_firmware_using_catalog.py.
We launched the command : python3 update_firmware_using_catalog_3.0.py --ip x.x.x.x--user admin --password  --updateactions upgrade --deviceid 88090

Instead of running only on the deviceid 88090, this command was executed on one hundred servers of our 1200 servers.

FYI, we got the deviceid by api (https://-----/api/DeviceService/Devices(88090)
{"@odata.context":"/api/$metadata#DeviceService.Device","@odata.type":"#DeviceService.Device","@odata.id":"/api/DeviceService/Devices(88090)","Id":88090,"Type":1000,"Identifier":"GRBNNR2","DeviceServiceTag":"GRBNNR2","ChassisServiceTag":"GR8WNR2","Model":"PowerEdge 

Do you have an explanation for this behavior?

regards,
Thibaud

**Comment by grantcurell** [comment]
@Thibaudm33 - I'll set it up in a lab and give it a test go and get back to you.

**Comment by grantcurell** [comment]
@Thibaudm33 - I was able to replicate the behavior. I haven't played with that script before. I'll go check into it now. Thanks for reporting this!

(My only target was .63)
![image](https://user-images.githubusercontent.com/35169230/98972050-ed271300-24df-11eb-9ef1-3c556e54ec71.png)

**Comment by grantcurell** [comment]
@Thibaudm33 could you confirm what version of OpenManage you're running?

![image](https://user-images.githubusercontent.com/35169230/98980839-27e27880-24eb-11eb-85e8-ee4bea4ec0f7.png)

It's in the top right. I tracked the problem down. On older versions of OpenManage (I tested on 3.4.1) the line:

    component_status, component_data = request(url=compl_url, header=headers)

which calls the API returns all hosts instead of just the one in the baseline. When I tested in OpenManage 3.5.0 the API correctly returned only one result.

**Comment by Thibaudm33** [comment]
@grantcurell Our version of OpenManage is 3.5.0 Build 60

![Capture](https://user-images.githubusercontent.com/67233470/99044562-3c2c8100-2590-11eb-8530-59ed5933f5eb.JPG)

**Comment by grantcurell** [comment]
@Thibaudm33 hmmm I have fewer ideas then. Does the job log for the firmware update job have all 100 devices in it?

## Mine from 3.4.1:
![image](https://user-images.githubusercontent.com/35169230/99077477-ce318b00-258a-11eb-807f-60c0d22d708d.png)

## Mine from 3.5.0 (build 60)
![image](https://user-images.githubusercontent.com/35169230/99077950-90813200-258b-11eb-8dbb-591eaf6d5854.png)

**Comment by Thibaudm33** [comment]
Yes, the firmware update job have all 100 devices

**Comment by grantcurell** [comment]
@Thibaudm33 two of us have checked it and didn't bump into anything, but that doesn't mean there aren't any problems there. If you're willing to do a Zoom or something and you've got a Python debugger handy I'd be willing to go take a look.

**Comment by grantcurell** [comment]
@Thibaudm33 just seeing if you want me to leave this open.

**Comment by grantcurell** [comment]
I'm going to go ahead and close this, but if you change your mind and want help I'm happy to troubleshoot it. You may have a scenario I just haven't tried yet.
